require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RemessasController do

  # This should return the minimal set of attributes required to create a valid
  # Remessa. As you add validations to Remessa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "codigorastreio" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RemessasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all remessas as @remessas" do
      remessa = Remessa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:remessas).should eq([remessa])
    end
  end

  describe "GET show" do
    it "assigns the requested remessa as @remessa" do
      remessa = Remessa.create! valid_attributes
      get :show, {:id => remessa.to_param}, valid_session
      assigns(:remessa).should eq(remessa)
    end
  end

  describe "GET new" do
    it "assigns a new remessa as @remessa" do
      get :new, {}, valid_session
      assigns(:remessa).should be_a_new(Remessa)
    end
  end

  describe "GET edit" do
    it "assigns the requested remessa as @remessa" do
      remessa = Remessa.create! valid_attributes
      get :edit, {:id => remessa.to_param}, valid_session
      assigns(:remessa).should eq(remessa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Remessa" do
        expect {
          post :create, {:remessa => valid_attributes}, valid_session
        }.to change(Remessa, :count).by(1)
      end

      it "assigns a newly created remessa as @remessa" do
        post :create, {:remessa => valid_attributes}, valid_session
        assigns(:remessa).should be_a(Remessa)
        assigns(:remessa).should be_persisted
      end

      it "redirects to the created remessa" do
        post :create, {:remessa => valid_attributes}, valid_session
        response.should redirect_to(Remessa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved remessa as @remessa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Remessa.any_instance.stub(:save).and_return(false)
        post :create, {:remessa => { "codigorastreio" => "invalid value" }}, valid_session
        assigns(:remessa).should be_a_new(Remessa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Remessa.any_instance.stub(:save).and_return(false)
        post :create, {:remessa => { "codigorastreio" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested remessa" do
        remessa = Remessa.create! valid_attributes
        # Assuming there are no other remessas in the database, this
        # specifies that the Remessa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Remessa.any_instance.should_receive(:update).with({ "codigorastreio" => "MyString" })
        put :update, {:id => remessa.to_param, :remessa => { "codigorastreio" => "MyString" }}, valid_session
      end

      it "assigns the requested remessa as @remessa" do
        remessa = Remessa.create! valid_attributes
        put :update, {:id => remessa.to_param, :remessa => valid_attributes}, valid_session
        assigns(:remessa).should eq(remessa)
      end

      it "redirects to the remessa" do
        remessa = Remessa.create! valid_attributes
        put :update, {:id => remessa.to_param, :remessa => valid_attributes}, valid_session
        response.should redirect_to(remessa)
      end
    end

    describe "with invalid params" do
      it "assigns the remessa as @remessa" do
        remessa = Remessa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Remessa.any_instance.stub(:save).and_return(false)
        put :update, {:id => remessa.to_param, :remessa => { "codigorastreio" => "invalid value" }}, valid_session
        assigns(:remessa).should eq(remessa)
      end

      it "re-renders the 'edit' template" do
        remessa = Remessa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Remessa.any_instance.stub(:save).and_return(false)
        put :update, {:id => remessa.to_param, :remessa => { "codigorastreio" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested remessa" do
      remessa = Remessa.create! valid_attributes
      expect {
        delete :destroy, {:id => remessa.to_param}, valid_session
      }.to change(Remessa, :count).by(-1)
    end

    it "redirects to the remessas list" do
      remessa = Remessa.create! valid_attributes
      delete :destroy, {:id => remessa.to_param}, valid_session
      response.should redirect_to(remessas_url)
    end
  end

end
